# Generated by Django 2.2.7 on 2020-06-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='parent_email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
