# Pull base image
FROM python:3.7


# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


# Set work directory
WORKDIR /code


# Install dependencies
COPY Pipfile Pipfile.lock /code/
RUN pip install pipenv && pipenv install --system



# Copy project
COPY . /code/

EXPOSE 80
# COPY cron.txt /etc/cron.d/cron-task
# RUN chmod 0644 /etc/cron.d/cron-task
# RUN service cron start

RUN apt update
RUN apt install -y cron


CMD /code/script_prod.sh