version: '3.7'

services:
    web:
        build: 
            context: .
            dockerfile: Dockerfile.prod
        environment:
            - ENVIRONMENT=production
            - SECRET_KEY=@^la7#2kl%8$$o9rl)8$$aqvrwq5_x1=r!xc-1p#+(!m4r2vue*&
            - DEBUG=0
            - EMAIL_HOST_USER=apikey
            - EMAIL_HOST_PASSWORD=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
        volumes:
            - .:/code
            # - ./code/staticfiles:/code/staticfiles
        networks:
            - nginx_network
            - db_network
        depends_on:
            - db
    nginx:
        image: nginx:1.17.0
        ports: 
            - 80:80
            - 443:443
        volumes:
            - ./staticfiles:/code/staticfiles
            - ./config/nginx/conf.d:/etc/nginx/conf.d
            # - ./code/staticfiles:/code/staticfiles
        depends_on: 
            - web
        networks:
            - nginx_network
              # command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s
              # reload; done & nginx -g \"daemon off;\"'"
    db:
        image: postgres:11
        env_file:
            - config/db/db_env
        networks:
            - db_network
        volumes:
            - db_volume:/var/lib/postgresql/data/
networks:
    nginx_network:
        driver: bridge
    db_network:
        driver: bridge
volumes:
    db_volume:
#    static_volume:

