# Generated by Django 2.2.7 on 2020-05-31 05:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('difficulty', models.CharField(choices=[('beginner', 'beginnger'), ('intermediate', 'intermediate'), ('advanced', 'advanced')], default='beginner', max_length=40)),
                ('cost', models.FloatField(null=True)),
                ('description', models.TextField(null=True)),
                ('slug', models.SlugField(default=None, unique=True)),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
