# Generated by Django 2.2.7 on 2020-06-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
