# Generated by Django 2.2.7 on 2020-06-02 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_payment_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='theclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_class', to='classes.Class'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
