# Generated by Django 2.2.7 on 2020-06-02 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20200602_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='theclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Class'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
