# Generated by Django 2.2.7 on 2020-06-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20200602_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='syllabus',
            field=models.TextField(null=True),
        ),
    ]
