# Generated by Django 2.2.7 on 2020-06-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_class_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='past_payment_deadline',
            field=models.BooleanField(default=False),
        ),
    ]
