# Generated by Django 2.2.7 on 2020-06-07 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_class_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classes.Class')),
            ],
        ),
    ]
