# Generated by Django 2.2.7 on 2020-06-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
