# Generated by Django 2.2.7 on 2020-06-13 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_auto_20200607_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ('name',)},
        ),
    ]
