# Generated by Django 2.2.7 on 2020-06-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0013_auto_20200613_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='language',
            field=models.CharField(choices=[('Django', 'Django'), ('Python', 'Python'), ('C++', 'C++'), ('Java', 'Java'), ('HTML5', 'HTML5')], default='Python', max_length=50),
        ),
    ]
