# Generated by Django 2.2.7 on 2020-06-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0014_auto_20200613_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=40),
        ),
    ]
