# Generated by Django 2.2.7 on 2020-07-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0015_auto_20200613_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='embedded_url',
            field=models.URLField(blank=True),
        ),
    ]
