# Generated by Django 2.2.7 on 2020-07-22 06:51

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0016_class_embedded_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='body',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
