# Generated by Django 2.2.7 on 2020-07-22 06:56

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0017_auto_20200722_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='syllabus',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
