# Generated by Django 2.2.7 on 2021-01-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0020_auto_20210117_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='third_day_optional',
        ),
        migrations.AlterField(
            model_name='class',
            name='second_day',
            field=models.CharField(blank=True, choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=50, null=True),
        ),
    ]
