# Generated by Django 2.2.7 on 2021-01-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0021_auto_20210117_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='class',
            name='end_date',
            field=models.DateField(),
        ),
    ]
