# Generated by Django 2.2.7 on 2021-01-24 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0023_auto_20210117_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='registration_deadline',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
