# Generated by Django 2.2.7 on 2020-06-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('summary', models.TextField(null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
