# Generated by Django 2.2.7 on 2020-07-22 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_lesson_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Class'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='summary',
            field=models.TextField(default='', null=True),
        ),
    ]
