# Generated by Django 2.2.7 on 2020-07-22 03:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_lesson_stuff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='summary',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
