# Generated by Django 2.2.7 on 2020-07-22 06:01

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_auto_20200721_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='stuff',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='homework',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
