# Generated by Django 2.2.7 on 2020-07-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_auto_20200727_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='embedded_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
